name: "Terraform Cloud Action"
description: "Action for working with Terraform Cloud"
author: "Rasmus Bo Jørgensen"
inputs:
  tfc_token:
    description: "Terraform Cloud API token"
    required: true
  tfc_organization:
    description: "Name of the Terraform Cloud organization"
    required: true
  tfc_client:
    description: "Name of the VCS client in Terraform Cloud to register the module with"
    required: true
  github_organization:
    description: "Name of the GitHub organization containing the repository"
    required: true
  repository:
    description: "Name of the GitHub repository containing the Terraform module"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tfc_token }}
    - ${{ inputs.tfc_organization }}
    - ${{ inputs.tfc_client }}
    - ${{ inputs.github_organization }}
    - ${{ inputs.repository }}
